namespace SpriteKind {
    export const NPC1 = SpriteKind.create()
    export const LoadSprite = SpriteKind.create()
    export const NPC2 = SpriteKind.create()
    export const NPC3 = SpriteKind.create()
    export const NPC4 = SpriteKind.create()
    export const LoadShip = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Hero.isHittingTile(CollisionDirection.Bottom)) {
        Hero.vy = -200
    }
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Endgame == 1) {
        Endgame = 0
        scene.setBackgroundImage(assets.image`Leave1`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Leave2`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Leave3`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Leave4`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Leave5`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Leave6`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Leave7`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Leave8`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Leave9`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Leave10`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Leave11`)
        pause(4000)
        Endgame = 2
    }
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (Endgame == 1) {
        Endgame = 0
        scene.setBackgroundImage(assets.image`Stay1`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay2`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay3`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay4`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay5`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay6`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay7`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay8`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay9`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay10`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay11`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Stay12`)
        pause(4000)
        Endgame = 2
    }
})
controller.anyButton.onEvent(ControllerButtonEvent.Released, function () {
    if (isTitleScreen == 1) {
        scene.setBackgroundImage(assets.image`InstructionScreen`)
        pauseUntil(() => controller.anyButton.isPressed())
        isTitleScreen = 2
    }
    if (isTitleScreen == 2) {
        isTitleScreen = 0
        scene.setBackgroundImage(assets.image`Intro1`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Intro2`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Intro3`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Intro4`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Intro5`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Intro6`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Intro7`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Intro8`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Intro9`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Intro10`)
        pause(4000)
        scene.setBackgroundImage(assets.image`Background_1`)
        tiles.setCurrentTilemap(tilemap`level_1`)
        NPC12 = sprites.create(assets.image`NPC1`, SpriteKind.NPC1)
        NPC12.setPosition(200, 25)
        NPC12.setScale(3, ScaleAnchor.Middle)
        LoadSprite1 = sprites.create(assets.image`AlienWalk_2`, SpriteKind.LoadSprite)
        LoadSprite2 = sprites.create(assets.image`AlienWalk_1`, SpriteKind.LoadSprite)
        LoadSprite3 = sprites.create(assets.image`GrassTile`, SpriteKind.LoadSprite)
        LoadSprite4 = sprites.create(assets.image`DirtTile`, SpriteKind.LoadSprite)
        CrashedShip = sprites.create(assets.image`CrashedShip`, SpriteKind.LoadShip)
        CrashedShip.setScale(3, ScaleAnchor.Middle)
        CrashedShip.setPosition(15, 225)
        sprites.destroyAllSpritesOfKind(SpriteKind.LoadSprite)
        Hero = sprites.create(assets.image`AlienWalk_1`, SpriteKind.Player)
        Hero.setStayInScreen(true)
        Hero.setPosition(15, 115)
        controller.moveSprite(Hero, 100, 0)
        Hero.ay = 500
        scene.cameraFollowSprite(Hero)
        music.setVolume(15)
        music.play(music.createSong(assets.song`Background Soundtrack`), music.PlaybackMode.LoopingInBackground)
    }
    if (Endgame == 2) {
        pauseUntil(() => controller.anyButton.isPressed())
        scene.setBackgroundImage(assets.image`TitleScreen`)
        isTitleScreen = 1
        Endgame = 0
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Hero,
    assets.animation`Walk_Cycle2`,
    200,
    true
    )
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC2, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.NPC2)
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
    tiles.setCurrentTilemap(tilemap`Blank`)
    scene.setBackgroundImage(assets.image`Novel2_1`)
    music.stopAllSounds()
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_2`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_3`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_4`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_5`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_6`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_7`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_8`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_9`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_10`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_11`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_12`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_13`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_14`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_15`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_16`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_17`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_18`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_19`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_20`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_21`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_22`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_23`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_24`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel2_25`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Background_2`)
    tiles.setCurrentTilemap(tilemap`level_3`)
    music.setVolume(15)
    music.play(music.createSong(assets.song`Background Soundtrack`), music.PlaybackMode.LoopingInBackground)
    Hero = sprites.create(assets.image`AlienWalk_1`, SpriteKind.Player)
    Hero.setStayInScreen(true)
    Hero.setPosition(15, 115)
    controller.moveSprite(Hero, 100, 0)
    Hero.ay = 500
    scene.cameraFollowSprite(Hero)
    NPC32 = sprites.create(assets.image`NPC3`, SpriteKind.NPC3)
    NPC32.setScale(3, ScaleAnchor.Middle)
    NPC32.setPosition(200, 25)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC3, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.NPC3)
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
    tiles.setCurrentTilemap(tilemap`Blank`)
    scene.setBackgroundImage(assets.image`Novel3_1`)
    music.stopAllSounds()
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_2`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_3`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_4`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_5`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_6`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_7`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_8`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_9`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_10`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_11`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_12`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_13`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_14`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_15`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_16`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_17`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_18`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_19`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_20`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_21`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_22`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_23`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_24`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_25`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_26`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel3_27`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Background_2`)
    tiles.setCurrentTilemap(tilemap`level_3`)
    music.setVolume(15)
    music.play(music.createSong(assets.song`Background Soundtrack`), music.PlaybackMode.LoopingInBackground)
    Hero = sprites.create(assets.image`AlienWalk_1`, SpriteKind.Player)
    Hero.setStayInScreen(true)
    Hero.setPosition(15, 115)
    controller.moveSprite(Hero, 100, 0)
    Hero.ay = 500
    scene.cameraFollowSprite(Hero)
    NPC42 = sprites.create(assets.image`NPC4`, SpriteKind.NPC4)
    NPC42.setScale(2, ScaleAnchor.Middle)
    NPC42.setPosition(200, 25)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC4, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.NPC4)
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
    tiles.setCurrentTilemap(tilemap`Blank`)
    scene.setBackgroundImage(assets.image`Novel4_1`)
    music.stopAllSounds()
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_2`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_3`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_4`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_5`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_6`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_7`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_8`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_9`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_10`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_11`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_12`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_13`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_14`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_15`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_16`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_17`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_18`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_19`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_20`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_21`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_22`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_23`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_24`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel4_25`)
    pause(4000)
    scene.setBackgroundImage(assets.image`ChoiceScreen`)
    Endgame = 1
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.NPC1, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.NPC1)
    sprites.destroyAllSpritesOfKind(SpriteKind.LoadShip)
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
    tiles.setCurrentTilemap(tilemap`Blank`)
    scene.setBackgroundImage(assets.image`Novel 1_1`)
    music.stopAllSounds()
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_2`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_3`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_4`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_5`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_6`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_7`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_8`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_9`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_10`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_11`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_12`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_13`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_14`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_15`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Novel 1_16`)
    pause(4000)
    scene.setBackgroundImage(assets.image`Background_1`)
    tiles.setCurrentTilemap(tilemap`level_2`)
    music.setVolume(15)
    music.play(music.createSong(assets.song`Background Soundtrack`), music.PlaybackMode.LoopingInBackground)
    Hero = sprites.create(assets.image`AlienWalk_1`, SpriteKind.Player)
    Hero.setStayInScreen(true)
    Hero.setPosition(15, 115)
    controller.moveSprite(Hero, 100, 0)
    Hero.ay = 500
    scene.cameraFollowSprite(Hero)
    NPC22 = sprites.create(assets.image`NPC2`, SpriteKind.NPC2)
    NPC22.setScale(3, ScaleAnchor.Middle)
    NPC22.setPosition(20, 25)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Hero,
    assets.animation`Walk_Cycle`,
    200,
    true
    )
})
let NPC22: Sprite = null
let NPC42: Sprite = null
let NPC32: Sprite = null
let CrashedShip: Sprite = null
let LoadSprite4: Sprite = null
let LoadSprite3: Sprite = null
let LoadSprite2: Sprite = null
let LoadSprite1: Sprite = null
let NPC12: Sprite = null
let Hero: Sprite = null
let Endgame = 0
let isTitleScreen = 0
scene.setBackgroundImage(assets.image`TitleScreen`)
isTitleScreen = 1
Endgame = 0
forever(function () {
    if (Endgame == 2) {
        scene.setBackgroundImage(assets.image`ThanksForPlaying`)
    }
})
